name = "GravitationalPotentials"
uuid = "c5ecfa00-e6a4-4f27-837b-868bffbab2ae"
authors = ["Abhro R. and contributors"]
version = "0.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
