name = "GravitationalPotentials"
uuid = "c5ecfa00-e6a4-4f27-837b-868bffbab2ae"
authors = ["Abhro R. and contributors"]
version = "0.0.0-DEV"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Integrals = "de52edbc-65ea-441a-8357-d3a637375a31"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
DocStringExtensions = "0.9"
Integrals = "4"
LinearAlgebra = "1.6"
julia = "1.6"
